


function y = forw_mod_fully3D_INTERF(x,transp)
% function y = forw_mod_fully3D_INTERF(x,transp)

global reconStruct_small;

if reconStruct_small.use_gpu == 0  % Matlab implementation

    y = forw_mod_fully3D_v2( x,transp,0 );

else  % GPU implementation

    % x_re_gpu = gpuArray(real(x));
    % x_im_gpu = gpuArray(imag(x));

    if strcmp(transp,'transp')==1        

        [reconStruct_small.x_re reconStruct_small.x_im] = feval( reconStruct_small.forw_mod_fully3D_cudaKernel_TRANSP_v1, ...
            reconStruct_small.x_re,reconStruct_small.x_im, ...
            real(x),imag(x), ...
            reconStruct_small.traj_mat, reconStruct_small.SEM_mat, ...
            reconStruct_small.b1m_re, reconStruct_small.b1m_im, ...
            reconStruct_small.b1p_re, reconStruct_small.b1p_im, ...
            reconStruct_small.b1_plus_echo_exp, ...
            reconStruct_small.freqs, sqrt(reconStruct_small.freq_weights), reconStruct_small.PE_field , ...
            reconStruct_small.nfreqs, ...
            reconStruct_small.nsamples, reconStruct_small.ncoils, reconStruct_small.nrots, ...
            reconStruct_small.nechoes, reconStruct_small.npix );

        y = reconStruct_small.x_re + 1j*reconStruct_small.x_im;
        % y = gather( reconStruct_small.x_re + 1j*reconStruct_small.x_im );
        % y = reconStruct_small.x_re + 1j*reconStruct_small.x_im;

    else

        [reconStruct_small.y_re reconStruct_small.y_im] = feval( reconStruct_small.forw_mod_fully3D_cudaKernel_v1, ...
            reconStruct_small.y_re,reconStruct_small.y_im, ...
            real(x),imag(x), ...
            reconStruct_small.traj_mat, reconStruct_small.SEM_mat, ...
            reconStruct_small.b1m_re, reconStruct_small.b1m_im, ...
            reconStruct_small.b1p_re, reconStruct_small.b1p_im, ...
            reconStruct_small.b1_plus_echo_exp, ...
            reconStruct_small.freqs, sqrt(reconStruct_small.freq_weights), reconStruct_small.PE_field , ...
            reconStruct_small.nfreqs, ...
            reconStruct_small.nsamples, reconStruct_small.ncoils, reconStruct_small.nrots, ...
            reconStruct_small.nechoes, reconStruct_small.npix );

        y = reconStruct_small.y_re + 1j*reconStruct_small.y_im;
        % y = gather( reconStruct_small.y_re + 1j*reconStruct_small.y_im );
        % y = reconStruct_small.y_re + 1j*reconStruct_small.y_im;

    end

    % reconStruct_small.g.FreeMemory

end

